service: apiml

runtime: python39
#api_version: 1
#threadsafe: true

#entrypoint: gunicorn -b :$PORT -w 2 main:app
entrypoint: uwsgi --http-socket :$PORT --wsgi-file main.py --callable app --master --processes 1 --threads 2

env_variables:
  # Set the GCP region to use for the App Engine app.
  # e.g. us-central1, europe-west1, asia-southeast1.
  # See https://cloud.google.com/compute/docs/regions-zones/
  # for a list of all regions.
  GOOGLE_CLOUD_REGION: asia-southeast2

instance_class: F2
#automatic_scaling:
  #min_instances: 1
  #max_instances: 1
  #min_idle_instances: 0
  #max_idle_instances: 0

handlers:
- url: /.*
  script: auto